'use strict';

/**
 * Catalogue of retail-banking feature areas.
 *
 * Each entry drives one lazy-loaded NgModule: a list page, a detail page, an
 * optional form page, a summary card component and a data service.
 */
const FEATURES = [
  {
    name: 'accounts',
    entity: 'account',
    icon: 'account_balance',
    entitlement: 'accounts:read',
    summary: 'Balances and account detail for every product the customer holds.',
    fields: [
      { name: 'nickname', label: 'Nickname', type: 'string' },
      { name: 'maskedNumber', label: 'Account', type: 'string' },
      { name: 'availableBalance', label: 'Available', type: 'money' },
      { name: 'currentBalance', label: 'Current', type: 'money' },
      { name: 'status', label: 'Status', type: 'status' },
    ],
    form: false,
  },
  {
    name: 'transfers',
    entity: 'transfer',
    icon: 'swap_horiz',
    entitlement: 'transfers:write',
    summary: 'Move money between own accounts and saved payees.',
    fields: [
      { name: 'reference', label: 'Reference', type: 'string' },
      { name: 'amount', label: 'Amount', type: 'money' },
      { name: 'scheduledFor', label: 'Scheduled', type: 'date' },
      { name: 'status', label: 'Status', type: 'status' },
    ],
    form: true,
  },
  {
    name: 'bill-pay',
    entity: 'bill',
    icon: 'receipt_long',
    entitlement: 'billpay:write',
    summary: 'Biller directory, one-off payments and standing instructions.',
    fields: [
      { name: 'biller', label: 'Biller', type: 'string' },
      { name: 'accountRef', label: 'Reference', type: 'string' },
      { name: 'amount', label: 'Amount', type: 'money' },
      { name: 'dueOn', label: 'Due', type: 'date' },
      { name: 'status', label: 'Status', type: 'status' },
    ],
    form: true,
  },
  {
    name: 'p2p-payments',
    entity: 'payment',
    icon: 'send',
    entitlement: 'p2p:write',
    summary: 'Person-to-person payments by phone number or handle.',
    fields: [
      { name: 'recipient', label: 'Recipient', type: 'string' },
      { name: 'handle', label: 'Handle', type: 'string' },
      { name: 'amount', label: 'Amount', type: 'money' },
      { name: 'status', label: 'Status', type: 'status' },
    ],
    form: true,
  },
  {
    name: 'cards',
    entity: 'card',
    icon: 'credit_card',
    entitlement: 'cards:read',
    summary: 'Card controls: freeze, replace, travel notices and PIN reset.',
    fields: [
      { name: 'network', label: 'Network', type: 'string' },
      { name: 'maskedNumber', label: 'Card', type: 'string' },
      { name: 'expiry', label: 'Expires', type: 'date' },
      { name: 'status', label: 'Status', type: 'status' },
    ],
    form: false,
  },
  {
    name: 'loans',
    entity: 'loan',
    icon: 'request_quote',
    entitlement: 'loans:read',
    summary: 'Personal loan balances, schedules and overpayment quotes.',
    fields: [
      { name: 'product', label: 'Product', type: 'string' },
      { name: 'outstanding', label: 'Outstanding', type: 'money' },
      { name: 'rate', label: 'Rate', type: 'number' },
      { name: 'nextPaymentOn', label: 'Next payment', type: 'date' },
    ],
    form: false,
  },
  {
    name: 'mortgage',
    entity: 'mortgage',
    icon: 'home_work',
    entitlement: 'mortgage:read',
    summary: 'Mortgage account view, rate switch eligibility and overpayments.',
    fields: [
      { name: 'property', label: 'Property', type: 'string' },
      { name: 'outstanding', label: 'Outstanding', type: 'money' },
      { name: 'rate', label: 'Rate', type: 'number' },
      { name: 'termEndsOn', label: 'Term ends', type: 'date' },
    ],
    form: false,
  },
  {
    name: 'investments',
    entity: 'holding',
    icon: 'trending_up',
    entitlement: 'investments:read',
    summary: 'Brokerage holdings, performance and dividend history.',
    fields: [
      { name: 'symbol', label: 'Symbol', type: 'string' },
      { name: 'units', label: 'Units', type: 'number' },
      { name: 'marketValue', label: 'Market value', type: 'money' },
      { name: 'gainLoss', label: 'Gain / loss', type: 'money' },
    ],
    form: false,
  },
  {
    name: 'statements',
    entity: 'statement',
    icon: 'description',
    entitlement: 'statements:read',
    summary: 'Downloadable statements and tax documents.',
    fields: [
      { name: 'period', label: 'Period', type: 'string' },
      { name: 'issuedOn', label: 'Issued', type: 'date' },
      { name: 'format', label: 'Format', type: 'string' },
    ],
    form: false,
  },
  {
    name: 'alerts',
    entity: 'alert',
    icon: 'notifications_active',
    entitlement: 'alerts:write',
    summary: 'Balance, spend and security alert subscriptions.',
    fields: [
      { name: 'trigger', label: 'Trigger', type: 'string' },
      { name: 'channel', label: 'Channel', type: 'string' },
      { name: 'threshold', label: 'Threshold', type: 'money' },
      { name: 'status', label: 'Status', type: 'status' },
    ],
    form: true,
  },
  {
    name: 'profile-settings',
    entity: 'preference',
    icon: 'manage_accounts',
    entitlement: 'profile:write',
    summary: 'Contact details, marketing preferences and security settings.',
    fields: [
      { name: 'label', label: 'Setting', type: 'string' },
      { name: 'value', label: 'Value', type: 'string' },
      { name: 'updatedOn', label: 'Updated', type: 'date' },
    ],
    form: true,
  },
  {
    name: 'onboarding',
    entity: 'application',
    icon: 'how_to_reg',
    entitlement: 'onboarding:write',
    summary: 'New product applications with identity and affordability steps.',
    fields: [
      { name: 'product', label: 'Product', type: 'string' },
      { name: 'stage', label: 'Stage', type: 'string' },
      { name: 'startedOn', label: 'Started', type: 'date' },
      { name: 'status', label: 'Status', type: 'status' },
    ],
    form: true,
  },
  {
    name: 'disputes',
    entity: 'dispute',
    icon: 'gavel',
    entitlement: 'disputes:write',
    summary: 'Raise and track transaction disputes and chargebacks.',
    fields: [
      { name: 'transactionRef', label: 'Transaction', type: 'string' },
      { name: 'reason', label: 'Reason', type: 'string' },
      { name: 'amount', label: 'Amount', type: 'money' },
      { name: 'raisedOn', label: 'Raised', type: 'date' },
      { name: 'status', label: 'Status', type: 'status' },
    ],
    form: true,
  },
  {
    name: 'rewards',
    entity: 'reward',
    icon: 'redeem',
    entitlement: 'rewards:read',
    summary: 'Cashback offers, points balance and redemption history.',
    fields: [
      { name: 'offer', label: 'Offer', type: 'string' },
      { name: 'merchant', label: 'Merchant', type: 'string' },
      { name: 'value', label: 'Value', type: 'money' },
      { name: 'expiresOn', label: 'Expires', type: 'date' },
    ],
    form: false,
  },
  {
    name: 'support-chat',
    entity: 'conversation',
    icon: 'support_agent',
    entitlement: 'support:read',
    summary: 'Secure messaging with the service team.',
    fields: [
      { name: 'subject', label: 'Subject', type: 'string' },
      { name: 'lastMessageOn', label: 'Last message', type: 'date' },
      { name: 'status', label: 'Status', type: 'status' },
    ],
    form: true,
  },
];

module.exports = { FEATURES };
